[package]
name = "simplicity-webide"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 'z'

[dependencies]
itertools = "0.11.0"
simplicity = { git = "https://github.com/uncomputable/rust-simplicity", branch = "no-sys", features = ["serde"] }
leptos = { version = "0.5.2", features = ["csr"] }
