[package]
name = "simplicity-webide"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.11.0"
simplicity = { git = "https://github.com/uncomputable/rust-simplicity", branch = "types", features = ["serde"] }
