[package]
name = "simplicity-webide"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 'z'

[dependencies]
itertools = "0.11.0"
simfony = { git = "https://github.com/uncomputable/simfony", branch = "dev" }
leptos = { version = "0.5.2", features = ["csr"] }
console_error_panic_hook = "0.1.7"
hex-conservative = "0.1.1"

[dev-dependencies]
wasm-bindgen-test = "0.3.40"
