[package]
name = "simplicity-webide"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 'z'
lto = true

[dependencies]
itertools = "0.13.0"
simfony = { git = "https://github.com/BlockstreamResearch/simfony", rev = "40a9c32dc09417ffe4bc2ced74801beb13da5422" }
leptos = { version = "0.6.14", features = ["csr"] }
console_error_panic_hook = "0.1.7"
hex-conservative = "0.1.1"
js-sys = "0.3.70"
web-sys = { version = "0.3.70", features = ["Navigator", "Clipboard"] }
either = "1.13.0"
wasm-bindgen-futures = "0.4.43"
gloo-timers = { version = "0.3.0", features = ["futures"] }
serde_json = "1.0.105"

[dev-dependencies]
wasm-bindgen-test = "0.3.43"
