[package]
name = "simplicity-webide"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 'z'
lto = true

[dependencies]
itertools = "0.13.0"
simfony = { git = "https://github.com/BlockstreamResearch/simfony", rev = "6137606dab17d27693b2fa3d624850ee5658de37" }
leptos = { version = "0.6.14", features = ["csr"] }
console_error_panic_hook = "0.1.7"
hex-conservative = "0.1.1"
js-sys = "0.3.70"

[dev-dependencies]
wasm-bindgen-test = "0.3.43"
